baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "mx-plc Documentation"
theme = "docsy"

[module]
  [[module.imports]]
    path = "github.com/google/docsy"

  [[module.imports]]
    path = "github.com/FortAwesome/Font-Awesome"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[params]
  disableLanguages = true
